#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
//#include "rdt.h"

#define BUFSIZE 30
#define FILEBUF 510
void error_handling(char *message);

int main(int argc, char ** argv){
        int sock;
        char message[BUFSIZE];
        int str_len, addr_size, i;
        int N = atoi(argv[3]); //SWS
        char debug[4];

		float LOSS_RATE;
		float ERR_RATE;
		char title[] = "Word.docx";
		char MSG[FILEBUF];
		int base = 1; //the seq number of the oldest unacked packet.
		int nextseqnum = 1;
		struct sockaddr_in serv_addr;
		struct sockaddr_in from_addr;
		
		if(argc != 5){
			printf("Usage : %s <IP> <port> <SWS> <on/off>\n", argv[0]);
			exit(1);
		}
		strcpy(debug, argv[4]);																							
		printf("ON/OFF: %s\n", debug);
		sock = socket(PF_INET, SOCK_DGRAM, 0);
		if(sock == -1) error_handling("UDP socket() error");
		memset(&serv_addr, 0, sizeof(serv_addr));
		serv_addr.sin_family = AF_INET;
		serv_addr.sin_addr.s_addr = inet_addr(argv[1]);
		serv_addr.sin_port = htons(atoi(argv[2]));
		//rdt_send(MSG);
		sendto(sock, title, strlen(title), 0, (struct sockaddr*)&serv_addr, sizeof(serv_addr));
		
		FILE *ptr;
		int ch;
		int idx;
		
		if((ptr = fopen("Word.docx", "rb")) == NULL){
																																																																		                fputs("Reading File Error!", stderr);
																																																																						exit(1);
																																																																			}
																																		  idx=0;
																																						MSG[0]='\0';
																																		  while((ch=fgetc(ptr))!= EOF){
																																		  /*check whether nextseqnum is in the window boundary, and if it is out of boundary then wait the possible sending time.
																																		  Our algorithm : don't get any character until*/
																																		  if(nextseqnum>=bas																										  sleep(1);																																																																                        continue;																																																																																																														                if(strlen(MSG)*4 < FILEBUF-10){ //'strlen(MSG)/4' means actually possessed? bytes because MSG[0](char) has 4 bytes.
																																																																																														                        sleep(1);
																																																																																																				                        continue;
																																																																																																										                }
																																																																																																														                if(strlen(MSG)*4 < FILEBUF-10){ //'strlen(MSG)/4' means actually possessed? bytes because MSG[0](char) has 4 bytes.
																																																																																																																		                                                                                //https://dojang.io/mod/page/view.php?id=33
																																																																																																																																						                        /*below code is for debugging code. try to check it :) */
																																																																																																																																												                        //printf("test! sizeof(MSG) == %d && sizeof(MSG)/sizeof(MSG[0]) == %d && strlen(MSG) == %d\n", sizeof(MSG), sizeof(MSG)/sizeof(MSG[0]), strlen(MSG));
																																																																																																																																																		                        MSG[idx++]=ch;
																																																																																																																																																								                        MSG[idx]='\0';
																																																																																																																																																														                        printf("%02X : ", ch); //each ch have 4byte. sizeof(ch) == 4
																																																																																																																																																																				                        /*For Test : printf("strlen(Msg) == %d\n", strlen(MSG));*/

																																																																																																																																																																										                }else{
																																																																																																																																																																														                        sendto(sock, MSG, sizeof(MSG), 0, (struct sockaddr*)&serv_addr, sizeof(serv_addr));
																																																																																																																																																																																				                        if(strcmp(debug, "on")==0)
																																																																																																																																																																																										                                printf("\nSend pkt: %d\n", nextseqnum);
																																																																																																																																																																																																		                        printf("MSG : %s\n", MSG);

																																																																																																																																																																																																								                        MSG[0] = ch; /*When while condition checked, program already get a next character,
																																																																																																																																																																																																														                                                  but this character is discarded when it pass through If condition.
																																																																																																																																																																																																																										                                                    So we need to store this character into the 1st index of next MSG.*/
																																																																																																																																																																																																																																							                        MSG[1] = '\0';
																																																																																																																																																																																																																																													                        idx=1;
																																																																																																																																																																																																																																																			                        //Note that you must do this command(base++, nextseqnum++) when Ack is arrived from server to me
																																																																																																																																																																																																																																																									                        //Note that when Ack comes, you should set 'Base == Ack#;'
																																																																																																																																																																																																																																																															                        //When should we increase 'nextseqnum'??

																																																																																																																																																																																																																																																																					                        nextseqnum++;
																																																																																																																																																																																																																																																																											                }

																																																																																																																																																																																																																																																																															        }


																																																																																																																																																																																																																																																																																	/*MyeongJoo's code
																																																																																																																																																																																																																																																																																	        FILE* ptr;
																																																																																																																																																																																																																																																																																			        char ch;

																																																																																																																																																																																																																																																																																					        //Opening file in reading mode
																																																																																																																																																																																																																																																																																							        ptr = fopen("Word.txt", "rb");

																																																																																																																																																																																																																																																																																									        if(NULL == ptr) {
																																																																																																																																																																																																																																																																																											                printf("file can't be opened\n");
																																																																																																																																																																																																																																																																																															                exit(1);
																																																																																																																																																																																																																																	        }
																																																																																																																																																																																																																																																																																																					        int idx=0;
																																																																																																																																																																																																																																																																																																							        //Printing what is written in file
																																																																																																																																																																																																																																																																																																									        //character by character using loop.
																																																																																																																																																																																																																																																																																																											        do{
																																																																																																																																																																																																																																																																																																													                ch = fgetc(ptr);
																																																																																																																																																																																																																																																																																																																	                if(ch !='\n'){
																																																																																																																																																																																																																																																																																																																					                        MSG[idx++]=ch;
																																																																																																																																																																																																																																																																																																																											                }else{
																																																																																																																																																																																																																																																																																																																															                        if(nextseqnum<base+N){
																																																																																																																																																																																																																																																																																																																																					                                sendto(sock, MSG, sizeof(MSG)/sizeof(MSG[0]), 0, (struct sockaddr*)&serv_addr, sizeof(serv_addr));
																																																																																																																																																																																																																																																																																																																																													                                if(strcmp(debug, "on")==0)
																																																																																																																																																																																																																																																																																																																																																					                                        printf("Send pkt: %d\n", nextseqnum);
																																																																																																																																																																																																																																																																																																																																																															                                printf("%s\n", MSG);
																																																																																																																																																																																																																																																																																																																																																																							                                idx=0;
																																																																																																																																																																																																																																																																																																																																																																															                                MSG[0] = '\0';
																																																																																																																																																																																																																																																																																																																																																																																							                                nextseqnum++;
																																																																																																																																																																																																																																																																																																																																																																																															                        }
																																																																																																																																																																																																																																																																																																																																																																																																					                        else{

																																																																																																																																																																																																																																																																																																																																																																																																											                        }
																																																																																																																																																																																																																																																																																																																																																																																																																	                }

																																																																																																																																																																																																																																																																																																																																																																																																																					                //Checking if character is not EOF.
																																																																																																																																																																																																																																																																																																																																																																																																																									                //If it is EOF stop reading
																																																																																																																																																																																																																																																																																																																																																																																																																													        } while(ch != EOF);
																																																																																																																																																																																																																																																																																																																																																																																																																															*/
																																																																																																																																																																																																																																																																																																																																																																																																																															        //Closing the file
																																																																																																																																																																																																																																																																																																																																																																																																																																	        fclose(ptr);

																																																																																																																																																																																																																																																																																																																																																																																																																																			        for(i=0 ; i<3 ; i++){
																																																																																																																																																																																																																																																																																																																																																																																																																																					                addr_size = sizeof(from_addr);
																																																																																																																																																																																																																																																																																																																																																																																																																																									                str_len = recvfrom(sock, message, BUFSIZE, 0, (struct sockaddr*) &from_addr, &addr_size);
																																																																																																																																																																																																																																																																																																																																																																																																																																													                message[str_len]='\0';
																																																																																																																																																																																																																																																																																																																																																																																																																																																	                printf("The message %d from the server: %s \n", i, message);
																																																																																																																																																																																																																																																																																																																																																																																																																																																					        }
																																																																																																																																																																																																																																																																																																																																																																																																																																																							        close(sock);
																																																																																																																																																																																																																																																																																																																																																																																																																																																									        return 0;
																																																																																																																																																																																																																																																																																																																																																																																																																																																											}																																																																																																																																																																																																																																																																																																																																																																																																																																																											void error_handling(char *message){
																																																																																																																																																																																																																																																																																																																																																																																																																																																											        fputs(message, stderr);
																																																																																																																																																																																																																																																																																																																																																																																																																																																													        fputc('\n', stderr);
																																																																																																																																																																																																																																																																																																																																																																																																																																																															        perror("에러내용은: ");
																																																																																																																																																																																																																																																																																																																																																																																																																																																																	        exit(1);
																																																																																																																																																																																																																																																																																																																																																																																																																																																																			}

